name: Docs Branch Build

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        run: git clone https://wildstang:${{ secrets.UPDATE_PAT }}@github.com/wildstang/${{ github.event.repository.name }}.git

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build javadoc with Gradle
        run: |
          cd ${{ github.event.repository.name }}
          ./gradlew javadoc

      - name: Push to destination repository
        run: |
          cd ${{ github.event.repository.name }}
          git config --global user.email "liam.fruzyna@wildstang.org"
          git config --global user.name "Automated Push"
          git add docs
          git commit -m "Javadoc build"
          git checkout -b docs
          git push --set-upstream origin docs --force
